### ISSUE TITLE
ED notifying property change errors

### ISSUE THREAD

**Issue by knownasilya** [lytics/ember-data-model-fragments#198]
Upon `model.save()` I get the following error:

```stack
TypeError: Cannot read property 'notify' of undefined
    at Object.ChainWatchers.notify (http://crcogct.localhost:3000/dashboard/assets/vendor.js:28475:17)
    at chainsDidChange (http://crcogct.localhost:3000/dashboard/assets/vendor.js:34505:9)
    at Object.propertyDidChange (http://crcogct.localhost:3000/dashboard/assets/vendor.js:34415:5)
    at contentPropertyDidChange (http://crcogct.localhost:3000/dashboard/assets/vendor.js:46339:32)
    at Object.apply (http://crcogct.localhost:3000/dashboard/assets/vendor.js:37154:18)
    at Object.sendEvent (http://crcogct.localhost:3000/dashboard/assets/vendor.js:30699:28)
    at ObserverSet.flush (http://crcogct.localhost:3000/dashboard/assets/vendor.js:34022:25)
    at Object.endPropertyChanges (http://crcogct.localhost:3000/dashboard/assets/vendor.js:34533:19)
    at _notifyProperties (http://crcogct.localhost:3000/dashboard/assets/vendor.js:127142:25)
    at InternalModel.adapterDidCommit (http://crcogct.localhost:3000/dashboard/assets/vendor.js:126466:19)
```

The property it notifies about is a fragment.

**Comment by jakesjews** [comment]
@knownasilya would it be possible to replicate the issue in an ember-twiddle?

**Comment by knownasilya** [comment]
I'm not sure how to replicate it either.. seems to only happen in one place, but other places use the same action/save combo. The only thing that is changed is `toggleProperty` is used on a record nested in that fragment.

**Comment by slindberg** [comment]
Sounds very similar to #173, which I've yet to be able to reproduce. Although using Ember 2.x doesn't appear to resolve it, [my last comment](https://github.com/lytics/ember-data-model-fragments/issues/173#issuecomment-199538062) on that issue applies to this one as well.

**Comment by knownasilya** [comment]
@slindberg see my comment here https://github.com/emberjs/ember.js/issues/13470#issuecomment-225264726 where @krisselden confirmed that it's a bug with Fragments & ED. Maybe he can help out.

**Comment by jakesjews** [comment]
@knownasilya I'll try digging into it. It looks like your NotifyError repo reproduces it pretty consistently so hopefully I can track it down.

**Comment by jakesjews** [comment]
@knownasilya I did a bit of digging and it looks like if I remove use of the PromiseProxy object and directly use the store then everything works ok. I'm not very familiar with PromiseProxy but maybe something is being overridden so that its missing something it needs?

**Comment by knownasilya** [comment]
I was thinking the same, but am unsure of what could be missing..
