### ISSUE TITLE
becomeDirty fires before root.loading state  finished loading 

### ISSUE THREAD

**Issue by jakubikan** [lytics/ember-data-model-fragments#219]
```
"Error: Attempted to handle event `becomeDirty` on <theme:5744286971cb2c0600ee0604> while in state root.loading. 
    at EmberError (http://localhost:4200/assets/vendor.js:25799:21)
    at InternalModel._unhandledEvent (http://localhost:4200/assets/vendor.js:150316:13)
    at InternalModel.send (http://localhost:4200/assets/vendor.js:150194:14)
    at Class.send (http://localhost:4200/assets/vendor.js:151095:34)
    at fragmentDidDirty (http://localhost:4200/assets/vendor.js:188493:14)
    at setFragmentValue (http://localhost:4200/assets/vendor.js:187479:52)
    at Class.set (http://localhost:4200/assets/vendor.js:187613:20)
    at ComputedProperty.computedPropertySet [as _set] (http://localhost:4200/assets/vendor.js:24477:28)
    at ComputedProperty.computedPropertySetWithSuspend [as setWithSuspend] (http://localhost:4200/assets/vendor.js:24457:19)
    at ComputedProperty.computedPropertySetEntry [as set] (http://localhost:4200/assets/vendor.js:24435:17)"
```

Any ideas what could be wrong?

**Comment by jakesjews** [comment]
Hmm not too sure. Would it be possible to reproduce it in a small ember app?

**Comment by jakubikan** [comment]
Well it does not happen, when i change routes (thru a link), but when the page gets refreshed.

**Comment by jakubikan** [comment]
Okay found the cause of the problem. Apparently we are using a set in the init hook of the model, which then becomes dirty. ( but the route is still loading)

**Comment by workmanw** [comment]
> Apparently we are using a set in the init hook of the model, which then becomes dirty.

Yeap. I've made that mistake in the past, even when not using fragments (but just regular models). I'm not sure what you're setting, but I've found a good solution normally is to use a computed property instead of using `init` to initialize a value.

**Comment by workmanw** [comment]
@jakubikan It sounds like you've found the issue, so I'm going to close this. One protip I'll share, in our application we have a lot of async realtime and peer to peer communications. We often have the need of setting a value, without actually dirtying the record. We have a base model class in our app that all models extend from. That base model class has a bunch of helpers, including the following:

```
pushChanges(payload) {
  let kind = this.constructor.modelName,
      id = this.get('id');

  // Copy the payload and add our Id to it.
  payload = Ember.copy(payload, true);
  payload.bckey = id;

  // Push the payload
  this.store.pushPayload({ [kind]: payload });

  // Promise for when the push is done
  return this.store.findRecord(kind, id);
}
```

Whenever we need to update a property without making it dirty we just call: `user.pushChanges({ commentCount: 100 });`. This works with fragments too, `blogPost.pushChanges({ stats: { viewed: 100 } });`

**Comment by jakubikan** [comment]
cool, thanks for the help, very appreciated. It was a lot to figure out when you start a new project. :)
