### ISSUE TITLE
snapshot.changedAttributes() is broken with fragments and Ember Data > 3.1

### ISSUE THREAD

**Issue by Gorzas** [lytics/ember-data-model-fragments#318]
In Ember Data they have removed [the usage of Ember.copy](https://github.com/emberjs/data/commit/23a87e8e7a7cd39e33ef877148f7d9e8f103c2ab#diff-67322a0874ff9f30dbdfc17e18916a4dR174) so when you use `snapshot.changedAtributes()` it expects that `this._changedAttributes[key]` is always an Array (now they are copying an element with slice instead of using Ember.copy).

The problem is with [this code of EDMF](https://github.com/lytics/ember-data-model-fragments/blob/master/addon/ext.js#L164-L170): it returns a Boolean instead of an Array. What's the utility of this change? 
I'm going to remove the `changedAttribute` method from this `model.reopen` to see what happens.

**Comment by Gorzas** [comment]
I have already removed the code but i have a test failing, don't know why it happens :thinking: 

```
Source: 	
TypeError: (0 , _emberMetal.get)(...).getURL is not a function
    at Class.<anonymous> (http://localhost:7357/assets/vendor.js:46173:53)
    at ComputedProperty.get (http://localhost:7357/assets/vendor.js:41212:36)
    at Class.CPGETTER_FUNCTION [as url] (http://localhost:7357/assets/vendor.js:39456:31)
    at Object.object (http://localhost:7357/assets/test-support.js:3391:17)
    at Object.parse (http://localhost:7357/assets/test-support.js:3263:20)
    at Object.object (http://localhost:7357/assets/test-support.js:3392:54)
    at Object.parse (http://localhost:7357/assets/test-support.js:3263:20)
    at Object.object (http://localhost:7357/assets/test-support.js:3392:54)
    at Object.parse (http://localhost:7357/assets/test-support.js:3263:20)
    at Object.array (http://localhost:7357/assets/test-support.js:3225:20)
```
