### ISSUE TITLE
Cannot read property serializerFor of null 

### ISSUE THREAD

**Issue by drevets** [lytics/ember-data-model-fragments#321]
After upgrading from Ember CLI 2.18 to 3.4.4, I am getting this error when running unit, acceptance, and integration tests: 

TypeError: Cannot read property 'serializerFor' of null
    at Class.deserializeSingle (http://localhost:56686/assets/vendor.js:208413:30)
    at Class.<anonymous> (http://localhost:56686/assets/vendor.js:208336:22)
    at Array.map (<anonymous>)
    at Class.deserializeFragmentArray [as deserialize] (http://localhost:56686/assets/vendor.js:208335:19)
    at http://localhost:56686/assets/vendor.js:226252:31
    at http://localhost:56686/assets/vendor.js:211807:18
    at Map.forEach (<anonymous>)
    at MapWithDeprecations.forEach (http://localhost:56686/assets/vendor.js:208629:42)
    at Function.eachTransformedAttribute (http://localhost:56686/assets/vendor.js:211806:48)
    at Class.applyTransforms (http://localhost:56686/assets/vendor.js:226245:17)

I'm using Ember Data at ~3.4.4, and Ember Data Model Fragments at 3.3.0. From what I can tell, this error only happens when running the tests. The actual app itself seems to be running fine. 

Any help would be much appreciated — thanks!

**Comment by igorduarte** [comment]
Facing exactly the same problem here.

```js
TypeError: Cannot read property 'serializerFor' of null
    at Class.serializeFragment [as serialize] (http://localhost:7357/assets/vendor.js:113980:30)
    at Class.serializeAttribute (http://localhost:7357/assets/vendor.js:132462:29)
    at snapshot.eachAttribute (http://localhost:7357/assets/vendor.js:132393:14)
    at Ember.get.forEach (http://localhost:7357/assets/vendor.js:117261:18)
    at Map.forEach (<anonymous>)
    at MapWithDeprecations.forEach (http://localhost:7357/assets/vendor.js:114199:24)
    at Function.eachAttribute (http://localhost:7357/assets/vendor.js:117260:37)
    at Class.eachAttribute (http://localhost:7357/assets/vendor.js:116665:24)
    at Snapshot.eachAttribute (http://localhost:7357/assets/vendor.js:119950:19)
    at Class.serialize (http://localhost:7357/assets/vendor.js:132392:16)
```

```json
"ember-cli-qunit": "^4.3.2"
"ember-data": "~3.4.0"
"ember-data-model-fragments": "3.3.0"
```
Any help would be much appreciated — thanks! +1

**Comment by thrashr888** [comment]
I have the same issue on the same versions. Upgrading to 4.0.0 breaks other things (`TypeError: _private.RecordData is undefined`).

**Comment by RobbieTheWagner** [comment]
We will not be backporting any fixes at this time. If anyone is experiencing similar issues on latest, please let us know!
